//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Materiais.RepositorioAzure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEngenharia
    {
        public string GUID { get; set; }
        public string GUID_TIPO_ITEM { get; set; }
        public string GUID_CATALOGO { get; set; }
        public string GUID_ITEM_PAI { get; set; }
        public Nullable<int> PnPID { get; set; }
    }
}
