//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Materiais.RepositorioSQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PnPTables
    {
        public string GUID { get; set; }
        public string TableName { get; set; }
        public string BaseTable { get; set; }
        public string Abstract { get; set; }
        public string PhysicalName { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<int> SyncTimestamp { get; set; }
        public string Sigla_BRASS { get; set; }
    }
}
