//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Materiais.RepositorioSQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGLA_CODIGO
    {
        public string GUID { get; set; }
        public string SIGLA { get; set; }
        public Nullable<double> DIMENSAO_MM { get; set; }
        public string SIGLA_PAI { get; set; }
        public string GUID_NORMA { get; set; }
    }
}
