//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brass.Materiais.Plant3dDiagramas.RepoSQLServerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PnPDrawings
    {
        public string Area { get; set; }
        public string Author { get; set; }
        public string Carimbo_Escala { get; set; }
        public string Carimbo_Nº_Brass { get; set; }
        public string Carimbo_Nº_Cliente { get; set; }
        public string Carimbo_Revisão { get; set; }
        public string Carimbo_Subtítulo_1 { get; set; }
        public string Carimbo_Subtítulo_2 { get; set; }
        public string Description { get; set; }
        public string Dwg_Name { get; set; }
        public string Path { get; set; }
        public string PnID { get; set; }
        public string PnPDrawingGuid { get; set; }
        public Nullable<bool> PnPDwgOutOfSync { get; set; }
        public long PnPID { get; set; }
        public string PnPParentGuid { get; set; }
        public Nullable<bool> PnPPromptForTemplate { get; set; }
        public string PnPRelativePath { get; set; }
        public string PnPTemplateFile { get; set; }
        public string PnPTemplateFileRelative { get; set; }
        public string PnPTemplateFileUnc { get; set; }
        public Nullable<System.Guid> PnPTimestampGuid { get; set; }
        public string PnPType { get; set; }
        public string PnPUnc { get; set; }
        public string Revision { get; set; }
        public string Title { get; set; }
        public string Carimbo_Área_do_Desenho { get; set; }
    }
}
